apiVersion: v1
kind: Namespace
metadata:
  name: educates-config
---
apiVersion: lookup.educates.dev/v1beta1
kind: ClientConfig
metadata:
  name: admin
  namespace: educates-config
spec:
  client:
    password: super-secret
  roles:
    - admin
---
apiVersion: lookup.educates.dev/v1beta1
kind: ClusterConfig
metadata:
  name: local-cluster
  namespace: educates-config
---
apiVersion: lookup.educates.dev/v1beta1
kind: TenantConfig
metadata:
  name: example-tenant
  namespace: educates-config
spec:
  clusters:
    nameSelector:
      matchNames:
        - local-cluster
---
apiVersion: lookup.educates.dev/v1beta1
kind: ClientConfig
metadata:
  name: custom-portal
  namespace: educates-config
spec:
  client:
    password: secret-password
  roles:
    - tenant
  tenants:
    - example-tenant
